name: polymer
version: 0.17.0-dev
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: >
  Polymer.dart is a new type of library for the web, built on top of Web
  Components, and designed to leverage the evolving web platform on modern
  browsers.
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  browser: '>=0.10.0 <0.11.0'
  html: '>=0.12.0 <0.13.0'
  initialize: '>=0.5.1+3 <0.7.0'
  polymer_interop: '>=0.2.0 <0.3.0'
  reflectable: 0.2.0
  test: '^0.12.3'
  web_components: '>=0.11.3 <0.13.0'
  reflectable: '0.2.0'
transformers:
- web_components
- test/pub_serve:
    $include: test/**_test{.*,}.dart
- reflectable:
    entry_points:
      - test/src/common/behavior_test.dart
      - test/src/common/behavior_composition_test.dart
      - test/src/common/js_proxy_test.dart
      - test/src/common/polymer_descriptor_test.dart
      - test/src/common/polymer_mixin_test.dart
      - test/src/common/polymer_register_test.dart
      - test/src/micro/attributes_test.dart
      - test/src/micro/lifecycle_callbacks_test.dart
      - test/src/mini/bottom_up_ready_test.dart
      - test/src/mini/default_values_test.dart
      - test/src/mini/dom_distribution_test.dart
      - test/src/mini/template_stamping_test.dart
      - test/src/standard/attribute_binding_test.dart
      - test/src/standard/computed_properties_test.dart
      - test/src/standard/event_listener_test.dart
      - test/src/standard/node_finding_test.dart
      - test/src/standard/property_binding_test.dart
      - test/src/standard/property_change_callbacks_test.dart
      - test/src/standard/property_change_notification_test.dart
      - test/src/standard/read_only_properties_test.dart
      - test/src/standard/reflect_to_attribute_test.dart
      - test/src/template/array_selector_test.dart
      - test/src/template/dom_bind_test.dart
      - test/src/template/dom_if_test.dart
      - test/src/template/dom_repeat_test.dart
dependency_overrides:
  polymer_interop:
    git:
      ref: 0.2.0-rc1
      url: https://github.com/dart-lang/polymer_interop.git
  analyzer: ^0.26.0
environment:
  sdk: '>=1.4.0 <2.0.0'
