name: polymer
version: 0.17.0-dev
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: >
  Polymer.dart is a new type of library for the web, built on top of Web
  Components, and designed to leverage the evolving web platform on modern
  browsers.
homepage: https://www.dartlang.org/polymer-dart/
dependencies:
  analyzer: '>=0.15.6 <0.26.0'
  args: '>=0.11.0 <0.14.0'
  barback: '>=0.14.2 <0.16.0'
  browser: '>=0.10.0 <0.11.0'
  code_transformers: '>=0.2.7 <0.3.0'
  html: '>=0.12.0 <0.13.0'
  initialize: '>=0.5.1+3 <0.7.0'
  logging: '>=0.9.2 <0.12.0'
  path: '>=0.9.0 <2.0.0'
  polymer_interop: '>=0.2.0 <0.3.0'
  smoke: '>=0.2.0 <0.4.0'
  source_maps: '>=0.9.4 <0.11.0'
  source_span: '>=1.0.0 <2.0.0'
  web_components: '>=0.11.3 <0.13.0'
  yaml: '>=0.9.0 <3.0.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
transformers:
- web_components

dependency_overrides:
  polymer_interop:
    git:
      ref: 0.2.0-dev
      url: https://github.com/dart-lang/polymer_interop.git

environment:
  sdk: '>=1.4.0 <2.0.0'
